//http://lg.lgames.net:88 为本地地址
//http://223.203.221.79:8088 为测试服地址
@test_url=http://lg.lgames.net:88

//数据统计 
// {
//   "page": 1）,
//   "pagesize": 20,
//   "channel_id": "渠道ID（非必填）",
//   "strTime":"起始时间"（非必填）,
//   "endTime":"结束时间（非必填）"
// }
POST {{test_url}}/index/Statisticsing/index HTTP/1.1

//参数
{
  "page": 1,
  "pagesize": 20,
  "channel_id": "",
  "strTime":"",
  "endTime":""
}
//返回值
//{
//    "code": 200,
//    "msg": "数据统计获取成功！",
//    "payload": {
//        "list": [
//            {
//                "datetime": "2018-12-13",                         =>时间
//                "channeles": [
//                    {
//                        "nickname": "测试专用",                      =>渠道名称
//                        "today_add_user": 1,                          =>新增用户
//                        "today_active_user": 0,                       =>活跃用户
//                        "today_start_up": 0,                          =>启动次数
//                        "user_total": 29,                             =>累计用户
//                        "best_gold": 0,                               =>下注金额
//                        "pay_gold": 0,                                =>下注金币
//                        "prize_win": 0,                               =>中奖金额
//                        "profit_loss": 1540,                          =>盈亏收益
//                        "play_pay_gold": 0                            =>用户购买金额
//                    },
//                    {
//                        "nickname": "开发专用",
//                        "today_add_user": 1,
//                        "today_active_user": 0,
//                        "today_start_up": 0,
//                        "user_total": 9,
//                        "best_gold": 0,
//                        "pay_gold": 744400,
//                        "prize_win": 378800,
//                        "profit_loss": 0,
//                        "play_pay_gold": 0
//                    }
//                ]
//            },
//            {
//                "datetime": "2018-12-12",
//                "channeles": [
//                    {
//                        "nickname": "测试专用",
//                        "today_add_user": 1,
//                        "today_active_user": 0,
//                        "today_start_up": 0,
//                        "user_total": 26,
//                        "best_gold": 0,
//                        "pay_gold": 0,
//                        "prize_win": 0,
//                        "profit_loss": 1540,
//                        "play_pay_gold": 0
//                    }
//                ]
//            }
//        ],
//        "page": 1,
//        "pageSize": 20,
//        "total": 2,
//        "ts": 1544669589
//    }
//}



//彩种统计 
// {
//   "page": 1）,
//   "pagesize": 20,
//   "channel_id": "渠道ID（非必填）",
//   "lottery_id":"彩种ID（非必填）",
//   "strTime":"起始时间"（非必填）,
//   "endTime":"结束时间（非必填）"
// }
POST {{test_url}}/index/Statisticsing/lotterylist HTTP/1.1

//参数
{
  "page": 1,
  "pagesize": 20,
  "channel_id": "",
  "lottery_id":"",
  "strTime":"",
  "endTime":""
}
//返回值
// {
//     "code": 200,
//     "msg": "彩种统计获取成功！",
//     "payload": {
//         "list": [
//             {
//                 "datetime": "2018-12-12",                           =>时间
//                 "channeles": [
//                     {
//                         "nickname": "开发专用",                      =>渠道名称
//                         "lottery_list": [
//                             {
//                                 "lottery_name": "新快3",            =>彩种名称
//                                 "pay_sum": 0,                        =>购买次数
//                                 "pay_people": 1,                     =>购买人数
//                                 "pay_gold": 0                        =>购买金额
//                             },
//                             {
//                                 "lottery_name": "好运11选5",
//                                 "pay_sum": 0,
//                                 "pay_people": 1,
//                                 "pay_gold": 0
//                             },
//                             {
//                                 "lottery_name": "老11选5",
//                                 "pay_sum": 0,
//                                 "pay_people": 2,
//                                 "pay_gold": 0
//                             },
//                             {
//                                 "lottery_name": "快3",
//                                 "pay_sum": 98,
//                                 "pay_people": 8,
//                                 "pay_gold": 0
//                             }
//                         ]
//                     }
//                 ]
//             }
//         ],
//         "page": 1,
//         "pageSize": 20,
//         "total": 1,
//         "ts": 0
//     }
// }



//彩票购买管理 
// {
//   "type":1,       //搜索类型
//   "strTime":0,    //开始时间
//   "endTime":0,    //结束时间
//   "content":"",    //搜索内容
//   "lottery_id":"" //彩票ID（预留字段暂时不用）
//   "channel_id":"" //渠道ID（预留字段暂时不用）
// }

POST {{test_url}}/index/NewLotteryBuy/index HTTP/1.1

{
  "page": 1,
  "pagesize": 20,
  "channel_id": "",
  "lottery_id":"",
  "strTime":"",
  "endTime":"",
  "type":"",
  "content":""
}

//返回值
// {
//     "code": 200,
//     "msg": "彩票管理-购买列表获取成功！",
//     "payload": {
//         "list": [
//             {
//                 "id": "5c19ed50e138232686df4376",
//                 "stage": "181219037",                          //期数
//                 "userName": "可口可乐了",                        //购买人
//                 "channelName": "姜测试专用",                     //渠道
//                 "order_number": "295279572616744960-",         //订单号
//                 "lotteryName": "快3",                          //彩种
//                 "status": "已开奖",                              //状态
//                 "playCard": [                                  //玩法和下注号码
//                     "和值/3",
//                     "和值/7",
//                     "和值/11",
//                     "和值/15",
//                     "和值/16",
//                     "和值/12",
//                     "和值/4",
//                     "和值/8",
//                     "和值/5",
//                     "和值/9",
//                     "和值/13",
//                     "和值/17",
//                     "和值/18",
//                     "和值/14",
//                     "和值/10",
//                     "和值/6"
//                 ],
//                 "amount": 0,                                   //获取购买金额
//                 "token": 3200                                  //购买金币
//             },
//             {
//                 "id": "5c19ecaae138232686df4373",
//                 "stage": "181219059",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295278877075312640-",
//                 "lotteryName": "重庆时时彩",
//                 "status": "未开奖",
//                 "playCard": [
//                     "三星组三/2,6",
//                     "三星组三/2,8",
//                     "三星组三/2,4",
//                     "三星组三/2,1",
//                     "三星组三/6,2",
//                     "三星组三/6,8",
//                     "三星组三/6,4",
//                     "三星组三/6,1",
//                     "三星组三/8,2",
//                     "三星组三/8,6",
//                     "三星组三/8,4",
//                     "三星组三/8,1",
//                     "三星组三/4,2",
//                     "三星组三/4,6",
//                     "三星组三/4,8",
//                     "三星组三/4,1",
//                     "三星组三/1,2",
//                     "三星组三/1,6",
//                     "三星组三/1,8",
//                     "三星组三/1,4"
//                 ],
//                 "amount": 0,
//                 "token": 20000
//             },
//             {
//                 "id": "5c19eb47e138232686df4370",
//                 "stage": "18121940",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295277387350806528-",
//                 "lotteryName": "11选5",
//                 "status": "已开奖",
//                 "playCard": [
//                     "任七/2,9,8,7,5,10,11",
//                     "任七/8,10,1,11,4,6,2",
//                     "任七/5,2,7,8,4,10,9"
//                 ],
//                 "amount": 0,
//                 "token": 600
//             },
//             {
//                 "id": "5c19eb0be138232686df436b",
//                 "stage": "18121939",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295277137974267904-",
//                 "lotteryName": "11选5",
//                 "status": "已开奖",
//                 "playCard": [
//                     "任七/5,10,4,3,9,8,2"
//                 ],
//                 "amount": 0,
//                 "token": 200
//             },
//             {
//                 "id": "5c19eaa2e138232686df4368",
//                 "stage": "181219036",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295276694862827520-",
//                 "lotteryName": "快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/3",
//                     "和值/7",
//                     "和值/11",
//                     "和值/15",
//                     "和值/16",
//                     "和值/12",
//                     "和值/8",
//                     "和值/4",
//                     "和值/9",
//                     "和值/13",
//                     "和值/17",
//                     "和值/5",
//                     "和值/6",
//                     "和值/10",
//                     "和值/14",
//                     "和值/18"
//                 ],
//                 "amount": 0,
//                 "token": 3200
//             },
//             {
//                 "id": "5c19e836e138232686df4364",
//                 "stage": "181219035",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295274097858842624-",
//                 "lotteryName": "快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/3",
//                     "和值/7",
//                     "和值/11",
//                     "和值/4",
//                     "和值/8",
//                     "和值/12",
//                     "和值/16",
//                     "和值/15",
//                     "和值/9",
//                     "和值/5",
//                     "和值/13",
//                     "和值/17",
//                     "和值/6",
//                     "和值/10",
//                     "和值/14",
//                     "和值/18"
//                 ],
//                 "amount": 0,
//                 "token": 3200
//             },
//             {
//                 "id": "5c19e63ce138232686df4361",
//                 "stage": "20181219031",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295271972697280512-",
//                 "lotteryName": "新快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/3",
//                     "和值/7",
//                     "和值/11",
//                     "和值/15",
//                     "和值/4",
//                     "和值/8",
//                     "和值/12",
//                     "和值/16",
//                     "和值/5",
//                     "和值/9",
//                     "和值/13",
//                     "和值/17",
//                     "和值/6",
//                     "和值/14",
//                     "和值/10",
//                     "和值/18"
//                 ],
//                 "amount": 0,
//                 "token": 3200
//             },
//             {
//                 "id": "5c19e3d8e138232686df435e",
//                 "stage": "18121935",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295269406919888896-",
//                 "lotteryName": "粤11选5",
//                 "status": "已开奖",
//                 "playCard": [
//                     "前三直选/6,8,5",
//                     "前三直选/4,8,5"
//                 ],
//                 "amount": 0,
//                 "token": 1200
//             },
//             {
//                 "id": "5c19e269e138232686df435b",
//                 "stage": "20181219030",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295267868637925376-",
//                 "lotteryName": "新快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/4",
//                     "和值/5",
//                     "和值/6",
//                     "和值/3",
//                     "和值/7",
//                     "和值/8"
//                 ],
//                 "amount": 0,
//                 "token": 1200
//             },
//             {
//                 "id": "5c19e142e138232686df4358",
//                 "stage": "18121939",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295266631519571968-",
//                 "lotteryName": "好运11选5",
//                 "status": "已开奖",
//                 "playCard": [
//                     "任二/4,8"
//                 ],
//                 "amount": 0,
//                 "token": 200
//             },
//             {
//                 "id": "5c19e13be138232686df4355",
//                 "stage": "18121939",
//                 "userName": "昵称唯一~",
//                 "channelName": "新测试",
//                 "order_number": "295266602893447168-",
//                 "lotteryName": "好运11选5",
//                 "status": "未开奖",
//                 "playCard": [
//                     "任二/4,8"
//                 ],
//                 "amount": 0,
//                 "token": 0
//             },
//             {
//                 "id": "5c19e129e138232686df4351",
//                 "stage": "181219035",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295266524220887040-",
//                 "lotteryName": "江苏快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/4",
//                     "和值/8",
//                     "和值/12",
//                     "和值/16",
//                     "和值/5",
//                     "和值/9",
//                     "和值/13",
//                     "和值/17",
//                     "和值/6",
//                     "和值/10",
//                     "和值/14",
//                     "和值/18",
//                     "和值/3",
//                     "和值/7",
//                     "和值/11",
//                     "和值/15"
//                 ],
//                 "amount": 0,
//                 "token": 160000
//             },
//             {
//                 "id": "5c19dce1e138232686df4349",
//                 "stage": "181219031",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295261929952251904-",
//                 "lotteryName": "快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/20",
//                     "和值/11",
//                     "和值/4",
//                     "和值/17",
//                     "和值/13",
//                     "和值/4"
//                 ],
//                 "amount": 0,
//                 "token": 1200
//             },
//             {
//                 "id": "5c19d96fe138232686df4346",
//                 "stage": "181219030",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295258229930201088-",
//                 "lotteryName": "快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/4",
//                     "和值/5"
//                 ],
//                 "amount": 0,
//                 "token": 400
//             },
//             {
//                 "id": "5c19c823e138232686df4343",
//                 "stage": "18121928",
//                 "userName": "温馨提示",
//                 "channelName": "新测试",
//                 "order_number": "295239657644363776-",
//                 "lotteryName": "好运11选5",
//                 "status": "已开奖",
//                 "playCard": [
//                     "任二/10,4"
//                 ],
//                 "amount": 0,
//                 "token": 200
//             },
//             {
//                 "id": "5c19c7afe138232686df4340",
//                 "stage": "181219024",
//                 "userName": "温馨提示",
//                 "channelName": "新测试",
//                 "order_number": "295239169104416768-",
//                 "lotteryName": "江苏快3",
//                 "status": "已开奖",
//                 "playCard": [
//                     "和值/5",
//                     "和值/9",
//                     "和值/8",
//                     "和值/12",
//                     "和值/11"
//                 ],
//                 "amount": 0,
//                 "token": 1000
//             },
//             {
//                 "id": "5c19c3a7e1382312329dce1e",
//                 "stage": "181219022",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295234840595271680-",
//                 "lotteryName": "江苏快3",
//                 "status": "未开奖",
//                 "playCard": [
//                     "和值/6",
//                     "和值/10"
//                 ],
//                 "amount": 0,
//                 "token": 0
//             },
//             {
//                 "id": "5c19c3a4e1382312329dce1b",
//                 "stage": "181219022",
//                 "userName": "可口可乐了",
//                 "channelName": "姜测试专用",
//                 "order_number": "295234830470221824-",
//                 "lotteryName": "江苏快3",
//                 "status": "未开奖",
//                 "playCard": [
//                     "和值/6",
//                     "和值/10"
//                 ],
//                 "amount": 0,
//                 "token": 0
//             },
//             {
//                 "id": "5c19c2fbe1382312329dce18",
//                 "stage": "181219019",
//                 "userName": "温馨提示",
//                 "channelName": "新测试",
//                 "order_number": "295234118487117824-",
//                 "lotteryName": "湖北快3",
//                 "status": "未开奖",
//                 "playCard": [
//                     "和值/5",
//                     "和值/9",
//                     "和值/8",
//                     "和值/12"
//                 ],
//                 "amount": 0,
//                 "token": 0
//             },
//             {
//                 "id": "5c19c2f7e1382312329dce15",
//                 "stage": "181219019",
//                 "userName": "温馨提示",
//                 "channelName": "新测试",
//                 "order_number": "295234102737506304-",
//                 "lotteryName": "湖北快3",
//                 "status": "未开奖",
//                 "playCard": [
//                     "和值/5",
//                     "和值/9",
//                     "和值/8",
//                     "和值/12"
//                 ],
//                 "amount": 0,
//                 "token": 0
//             }
//         ],
//         "page": 1,
//         "pageSize": 20,
//         "total": 160,
//         "ts": 0,
//         "type": "",
//         "content": "",
//         "lotteryNameList": [
//             {
//                 "id": "5c08e44ff2aa3dc9d132b13b",
//                 "name": "快3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b13d",
//                 "name": "江苏快3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b13f",
//                 "name": "新快3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b141",
//                 "name": "湖北快3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b145",
//                 "name": "11选5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b147",
//                 "name": "老11选5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b149",
//                 "name": "粤11选5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b14b",
//                 "name": "好运11选5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b14f",
//                 "name": "重庆时时彩"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b143",
//                 "name": "易快3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b14d",
//                 "name": "易乐11选5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b151",
//                 "name": "新时时彩"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b153",
//                 "name": "双色球"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b155",
//                 "name": "大乐透"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b157",
//                 "name": "3D"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b159",
//                 "name": "排列3"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b15b",
//                 "name": "排列5"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b15d",
//                 "name": "7星彩"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b15f",
//                 "name": "7乐彩"
//             },
//             {
//                 "id": "5c08e44ff2aa3dc9d132b161",
//                 "name": "快乐扑克"
//             }
//         ]
//     }
// }


//彩票购买管理 
// {
//   "order_number":1,       //订单ID
// }

POST {{test_url}}/index/NewLotteryBuy/orderItem HTTP/1.1

{
	"order_number":"5c08eab0e138233dc90e02b1"
}

//返回值
// {
//     "code": 200,
//     "msg": "成功",
//     "payload": {
//         "list": {
//             "order_number": "290603830326857728",          //订单号
//             "created": 1544088240308,                      /下注时间
//             "created_es": "2018-12-06 17:24:00",           /下注时间
//             "paid": 1544088240377,                         //购买时间
//             "paid_es": "2018-12-06 17:24:00",              //购买时间
//             "times": 1,                                    //倍数
//             "chase": 1,                                    //已追期
//             "chase_sum": 1,                                //总期数
//             "amount": 0,                                   //获取购买金额
//             "token": 1600                                  //购买金币
//         },
//         "order_number": "5c08eab0e138233dc90e02b1"         //订单号
//     }
// }